### ISSUE TITLE
Use `perf_event_open` directly instead of executing `perf stat`.

### ISSUE THREAD

**Issue by ConnorDoyle** [intelsdi-x/snap-plugin-collector-perfevents#18]
See http://man7.org/linux/man-pages/man2/perf_event_open.2.html

**Comment by lmroz** [comment]
Some additional info:
If we want to collect event defined symbolically (ex. `uncore_cbox_3/event=0x34,umask=0x11,name=unc_cbo_cache_lookup_read_m_uncore_cbox_3/`) we have to parse `/sys/bus/event_source/devices/[pmu here]/format/` to discover what config fields we have (ex. `event`, `umask`) and what is their bit position in `perf_event_attr.config` and `perf_event_attr.type` is value from `/sys/bus/event_source/devices/[pmu here]/type`.

**Comment by andrzej-k** [comment]
Closing this issue in favor of #38
