### ISSUE TITLE
error on the perfevents collector

### ISSUE THREAD

**Issue by solrac901** [intelsdi-x/snap-plugin-collector-perfevents#21]
Hi im trying to use the perfevent collector im receiving this error: 
GetMetricTypes call error : insufficient perf event subsystem capabilities any idea?
Thanks

DEBU[0052] wrote 7515280 to /tmp/143431745/snap-plugin-collector-perfevents
INFO[0052] Loading plugin: /tmp/143431745/snap-plugin-collector-perfevents  _module=_mgmt-rest
INFO[0052] plugin load called                            _block=load _module=control
INFO[0052] plugin load called                            _block=load-plugin _module=control-plugin-mgr path=snap-plugin-collector-perfevents
DEBU[0052] timeout chan start                            _block=waitHandling _module=control-plugin-execution
DEBU[0052] response chan start                           _block=waitHandling _module=control-plugin-execution
DEBU[0052] kill chan start                               _block=waitHandling _module=control-plugin-execution
DEBU[0053] plugin response (ok) received                 _block=waitHandling _module=control-plugin-execution
DEBU[0053] Getting plugin config                         _block_=getPluginConfigDataNode _module=config config-cache-key=0:perfevents:5 config-cache-value=&{0xc820180670 map[]}
ERRO[0053] error in getting metric types                 _block=load-plugin _module=control-plugin-mgr error=GetMetricTypes call error : insufficient perf event subsystem capabilities plugin-type=collector
ERRO[0053] GetMetricTypes call error : insufficient perf event subsystem capabilities  _module=_mgmt-rest
DEBU[0053] Removing file (/tmp/143431745/snap-plugin-collector-perfevents)  _module=_mgmt-rest
INFO[0053] API response                                  _module=_mgmt-rest index=2 method=POST status=Internal Server Error status-code=500 url=/v1/plugins

**Comment by geauxvirtual** [comment]
What do you get if you run `cat /proc/sys/kernel/perf_event_paranoid`? It seems the error you received is thrown if the value returned from `/proc/sys/kernel/perf_event_paranoid` is 1 or greater. https://github.com/intelsdi-x/snap-plugin-collector-perfevents/blob/master/perfevents/perfevents.go#L206-L208

**Comment by andrzej-k** [comment]
That's right - it's also listed in System Requirements section of the README: https://github.com/intelsdi-x/snap-plugin-collector-perfevents#system-requirements :wink:

**Comment by solrac901** [comment]
My bad, thanks for the help  this will resolve the issue :)

sudo sh -c "echo -0 > /proc/sys/kernel/perf_event_paranoid"

Regards,

2016-02-04 2:40 GMT-06:00 Andrzej Kuriata <notifications@github.com>:
