### ISSUE TITLE
Add CPU statistics (list of events to the perf command to capture the value of each event, raw PMC counters).

### ISSUE THREAD

**Issue by solrac901** [intelsdi-x/snap-plugin-collector-perfevents#25]
We need to use this collector to store these results, 
perf  stat -a -e r0100 -x ',' -o ${RESULTS_PATH}${RESULTS_SUFIX}_${TSTAMP} sleep 1  
Regards.

**Comment by andrzej-k** [comment]
Hey @solrac901 Thanks for reporting your use case. I've opened a new issue to capture all enhancement ideas. Let me close this issue and continue working on #38. Thank you.
