### ISSUE TITLE
Invalid metric value strconv.ParseUint: parsing "<not supported>": invalid syntax

### ISSUE THREAD

**Issue by beyossi** [intelsdi-x/snap-plugin-collector-perfevents#26]
I am creating a task using: ./snapctl task create -t json/perf-cpu-cache.json
it looks like everything is perfect:
Using task manifest to create task
Task created
ID: f19029e9-e91f-442d-840c-6fd9f35f7d8f
Name: Task-f19029e9-e91f-442d-840c-6fd9f35f7d8f
State: Running

attached is the json file renamed to txt.

however it starts to print out warnings and error messages to the console (see attached consolelog.txt).
checking the task status i get: "could not select a plugin".

attached is the stderr output.

I tries several options of metrics to collect in the task but i get those errors for all oof them.
perf version is 3.13.9.

plugin details are:
NAME             VERSION         TYPE            SIGNED          STATUS          LOADED TIME
perfevents       6               collector       false           loaded          Wed, 01 Jun 2016 11:16:45 IDT

[consolelog.txt](https://github.com/intelsdi-x/snap-plugin-collector-perfevents/files/293100/consolelog.txt)
[perf-cpu-cache.json.txt](https://github.com/intelsdi-x/snap-plugin-collector-perfevents/files/293102/perf-cpu-cache.json.txt)
[snap-plugin-collector-perfevents.stderr.txt](https://github.com/intelsdi-x/snap-plugin-collector-perfevents/files/293108/snap-plugin-collector-perfevents.stderr.txt)

**Comment by beyossi** [comment]
Any comment regarding this one? i am willing to provide any required data.
Sorry for urging,  this issue prevents me from progressing. 

Thanks

**Comment by beyossi** [comment]
Any comment regarding this one? i am willing to provide any required data.
Sorry for urging,  this issue prevents me from progressing. 

Thanks

**Comment by IRCody** [comment]
@beyossi: Can you provide what version of the plugin you are using? or if building from source the commit you are on.

**Comment by IRCody** [comment]
Looking into it a bit more it seems like stalled-cycles-frontend may not be supported with your perf version. Can you also provide the output of: 
`perf stat ls`

**Comment by beyossi** [comment]
plugin version is 6

perf stat ls output is:

0  createmetrics.sh  log  snapctl  snapd  snapd-config.json  tmp  tmp.log

 Performance counter stats for 'ls':

          0.817631 task-clock (msec)         #    0.677 CPUs utilized          
                 2 context-switches          #    0.002 M/sec                  
                 1 cpu-migrations            #    0.001 M/sec                  
               241 page-faults               #    0.295 M/sec                  
           1949084 cycles                    #    2.384 GHz                    
   <not supported> stalled-cycles-frontend 
   <not supported> stalled-cycles-backend  
           1604739 instructions              #    0.82  insns per cycle        
            315157 branches                  #  385.451 M/sec                  
             13303 branch-misses             #    4.22% of all branches        

       0.001208338 seconds time elapsed

**Comment by IRCody** [comment]
Markdown is mucking your paste, but this is what you are seeing correct?

```
          0.817631 task-clock (msec)         #    0.677 CPUs utilized          
                 2 context-switches          #    0.002 M/sec                  
                 1 cpu-migrations            #    0.001 M/sec                  
               241 page-faults               #    0.295 M/sec                  
           1949084 cycles                    #    2.384 GHz                    
   <not supported> stalled-cycles-frontend 
   <not supported> stalled-cycles-backend  
           1604739 instructions              #    0.82  insns per cycle        
            315157 branches                  #  385.451 M/sec                  
             13303 branch-misses             #    4.22% of all branches        

       0.001208338 seconds time elapsed
```

It seems like the `stalled-cycles-frontend` perf event is not supported on your system. This seems like an issue with parsing `<not supported>` (which is causing the plugin to panic). The improvements that I think   need to be made are to check for the `<not supported>` string and error if found giving the user a reasonable error message.

**Comment by beyossi** [comment]
thanks.
I am using "Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz".
what should I do to support the stalled-cycles-frontend and stalled-cycles-backend?
is it a matter of chip compliance?

I believe there should be a possibility to ignore a "not supported" component and still get measurements for the rest of the supported components.
Do you see any problem with that?

**Comment by solrac901** [comment]
will be better if the plugin cant help me to know which ones are supported,
in a readme file or just telling me go here an you can check which ones can
be extracted.
regards,.

2016-06-07 10:15 GMT-05:00 beyossi <notifications@github.com>:

**Comment by beyossi** [comment]
but anyway it requires the plugin to provide measurements of supported components while currently it doesn't, which makes the entire plugin useless for a machine with a Not-Supported component.

should I open a separate issue for such a fix?

**Comment by IRCody** [comment]
@beyossi -- I relabeled this one as bug since it already has links to your task files and the context/discussion.

I agree that "not supported" messages should definitely not cause panics, and should probably be a warning in the log. Basically skip over those sections while writing to the log what is happening that way metrics that are supported could still be collected.

**Comment by beyossi** [comment]
any idea when this fix should be available?, i.e. is it a matter of days/weeks?

**Comment by IRCody** [comment]
@beyossi: I am going to attempt to put in a fix for this tomorrow. I think it should be relatively straightforward. I will link this issue with the PR when it is ready or update if I'm not able to get to it tomorrow.

**Comment by IRCody** [comment]
@beyossi: I looked at this today and it is a little more involved than I thought so I am going to have to continue work on it next week. I will try to keep this issue updated.

**Comment by beyossi** [comment]
@IRCody: any updates regarding this one?

**Comment by IRCody** [comment]
@beyossi: Sorry for not updating. I haven't had much of a chance to look into it more. 

@intelsdi-x/plugin-maintainers: Can anyone else pick this up to look at?
